name: Android CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - master
    paths-ignore:
      - 'README.md'
      - 'fastlane/**'
  push:
    branches:
      - dev
      - master
    paths-ignore:
      - 'README.md'
      - 'fastlane/**'

jobs:
  build-and-test-jvm:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: gradle/wrapper-validation-action@v1

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
          java-version: 11
          distribution: "temurin"
          cache: 'gradle'

    - name: Build debug APK
      run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app/build/outputs/apk/debug/*.apk
